### ISSUE TITLE
The Name of the event breaks 

### ISSUE THREAD

**Issue by Valenie** [ajency/event-codes#12]
![image](https://cloud.githubusercontent.com/assets/19943710/26771951/1cc189b2-49e0-11e7-94f3-29674dcb0578.png)

**Comment by antoniojfurtado** [comment]
@renukaajency 
in class .aj-table__title we are using     /* word-break: break-all; */
Is this required from a better visibility standpoint? If so then not an issue.
OR 
@Valenie we can discuss if the word should not break

**Comment by renukaajency** [comment]
@antoniojfurtado 
https://github.com/ajency/events-wordpress-plugin/issues/19
was why that css was added...
