### ISSUE TITLE
The arrow besides view all has a line below

### ISSUE THREAD

**Issue by Valenie** [ajency/event-codes#17]
Theme: https://colorlib.com/wp/themes/illdy/ (Bootstrap)

![image](https://cloud.githubusercontent.com/assets/19943710/26823826/ac1f480a-4acc-11e7-9370-354d689d87eb.png)

**Comment by renukaajency** [comment]
Its because of the theme, its adding an underline to all anchor tags. I've tried to fix it, check and tell

**Comment by renukaajency** [comment]
Theme css is still overwriting, its a theme issue
